### ISSUE TITLE
Latest CsoundQT doesn't build

### ISSUE THREAD

**Issue by eriqk** [CsoundQt/csoundqt.github.io#1]
Hi all.
Got the latest CsoundQT from Git and tried to build. First with qmake from the command line, after that I decided to use Qt Creator.
Both times I got this:

```
/usr/include/c++/4.9/bits/c++0x_warning.h:32: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
```

I added 

```
CONFIG += c++11
```

to the qmake.pro file but that didn't seem to help.

I'm on Debian Jessie. Gcc 4.9.2, Qt 5.

Regards, Erik Maes

**Comment by tarmoj** [comment]
Hi,
Can you point out, which file or compilation command  causes the error
(please a bit more from the compilation output)?
What is your qmake output? C++11 should be added by default...

Tarmo


17.06.2017 18:27 kirjutas kuupäeval "er defaiqk" <notifications@github.com>:

Hi all.
Got the latest CsoundQT from Git and tried to build. First with qmake from
the command line, after that I decided to use Qt Creator.
Both times I got this:

/usr/include/c++/4.9/bits/c++0x_warning.h:32: error: #error This file
requires compiler and library support for the ISO C++ 2011 standard.
This support is currently experimental, and must be enabled with the
-std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^

I added

CONFIG += c++11

to the qmake.pro file but that didn't seem to help.

I'm on Debian Jessie. Gcc 4.9.2, Qt 5.

Regards, Erik Maes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CsoundQt/csoundqt.github.io/issues/1>, or mute the
thread

**Comment by tarmoj** [comment]
Hi,

I had similar problem building on one Linux machine today. 

I needed to add

CONFIG += c++11

to qcs.pro file. I commited it and pushed to develop branch. Please pull and see if it solves your 
problem (hopefully it does not break it for other builds... needs testing)

tarmo
